// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes  = "ApiKeyAuth.Scopes"
	ApiKeyQueryScopes = "ApiKeyQuery.Scopes"
)

// Defines values for ContentStatusResponseDataStatus.
const (
	NotFound ContentStatusResponseDataStatus = "not_found"
	Queued   ContentStatusResponseDataStatus = "queued"
	Stored   ContentStatusResponseDataStatus = "stored"
)

// Valid indicates whether the value is a known member of the ContentStatusResponseDataStatus enum.
func (e ContentStatusResponseDataStatus) Valid() bool {
	switch e {
	case NotFound:
		return true
	case Queued:
		return true
	case Stored:
		return true
	default:
		return false
	}
}

// Defines values for DetailedHealthResponseStatus.
const (
	DetailedHealthResponseStatusDegraded  DetailedHealthResponseStatus = "degraded"
	DetailedHealthResponseStatusHealthy   DetailedHealthResponseStatus = "healthy"
	DetailedHealthResponseStatusUnhealthy DetailedHealthResponseStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the DetailedHealthResponseStatus enum.
func (e DetailedHealthResponseStatus) Valid() bool {
	switch e {
	case DetailedHealthResponseStatusDegraded:
		return true
	case DetailedHealthResponseStatusHealthy:
		return true
	case DetailedHealthResponseStatusUnhealthy:
		return true
	default:
		return false
	}
}

// Defines values for MetricsResponseHealthStatus.
const (
	MetricsResponseHealthStatusDegraded  MetricsResponseHealthStatus = "degraded"
	MetricsResponseHealthStatusHealthy   MetricsResponseHealthStatus = "healthy"
	MetricsResponseHealthStatusUnhealthy MetricsResponseHealthStatus = "unhealthy"
)

// Valid indicates whether the value is a known member of the MetricsResponseHealthStatus enum.
func (e MetricsResponseHealthStatus) Valid() bool {
	switch e {
	case MetricsResponseHealthStatusDegraded:
		return true
	case MetricsResponseHealthStatusHealthy:
		return true
	case MetricsResponseHealthStatusUnhealthy:
		return true
	default:
		return false
	}
}

// BackupRequest defines model for BackupRequest.
type BackupRequest struct {
	// BackupName Optional custom backup name
	BackupName *string `json:"backup_name,omitempty"`

	// Immediate Force immediate backup
	Immediate *bool `json:"immediate,omitempty"`
}

// BackupResponse defines model for BackupResponse.
type BackupResponse struct {
	Data *struct {
		BackupPath      *string    `json:"backup_path,omitempty"`
		BackupSizeBytes *int64     `json:"backup_size_bytes,omitempty"`
		CreatedAt       *time.Time `json:"created_at,omitempty"`
		Message         *string    `json:"message,omitempty"`
		Success         *bool      `json:"success,omitempty"`
	} `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// CleanupResponse defines model for CleanupResponse.
type CleanupResponse struct {
	Data *struct {
		// DurationMs Duration of the cleanup operation in milliseconds
		DurationMs      *int64 `json:"duration_ms,omitempty"`
		RemovedTrackers *int   `json:"removed_trackers,omitempty"`
	} `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// Content defines model for Content.
type Content struct {
	// AccessCount Current number of retrievals
	AccessCount *int64 `json:"access_count,omitempty"`

	// AccessLimit Maximum allowed accesses
	AccessLimit *int `json:"access_limit,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Data Content data (format depends on type)
	Data *string `json:"data,omitempty"`

	// ExpiresAt Expiration timestamp
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	Id        *string    `json:"id,omitempty"`

	// Tag Content tag for categorization
	Tag *string `json:"tag,omitempty"`

	// Type MIME type
	Type *string `json:"type,omitempty"`
}

// ContentListResponse defines model for ContentListResponse.
type ContentListResponse struct {
	Data *struct {
		Contents *[]Content `json:"contents,omitempty"`

		// Filters Applied filters
		Filters *map[string]string `json:"filters,omitempty"`

		// Limit Number of items per page
		Limit *int `json:"limit,omitempty"`

		// Offset Number of items skipped
		Offset *int `json:"offset,omitempty"`

		// Total Total number of items matching the filter
		Total *int `json:"total,omitempty"`
	} `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// ContentStatusResponse defines model for ContentStatusResponse.
type ContentStatusResponse struct {
	Data *struct {
		Id     *string                          `json:"id,omitempty"`
		Status *ContentStatusResponseDataStatus `json:"status,omitempty"`
	} `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// ContentStatusResponseDataStatus defines model for ContentStatusResponse.Data.Status.
type ContentStatusResponseDataStatus string

// CountResponse defines model for CountResponse.
type CountResponse struct {
	Data *struct {
		Count *int `json:"count,omitempty"`
	} `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// DetailedHealthResponse defines model for DetailedHealthResponse.
type DetailedHealthResponse struct {
	Metrics *struct {
		BackupStatus   *string    `json:"backup_status,omitempty"`
		ContentCount   *int       `json:"content_count,omitempty"`
		DatabaseStatus *string    `json:"database_status,omitempty"`
		DiskUsage      *int64     `json:"disk_usage,omitempty"`
		GcStatus       *string    `json:"gc_status,omitempty"`
		LastBackup     *time.Time `json:"last_backup,omitempty"`
		MemoryUsage    *int64     `json:"memory_usage,omitempty"`

		// QueueMetrics Write queue metrics for monitoring
		QueueMetrics *struct {
			// QueueDepth Current number of items in the write queue
			QueueDepth *int `json:"queue_depth,omitempty"`

			// TotalErrors Total number of processing errors
			TotalErrors *int64 `json:"total_errors,omitempty"`

			// TotalProcessed Total number of items successfully processed
			TotalProcessed *int64 `json:"total_processed,omitempty"`

			// TotalQueued Total number of items ever queued
			TotalQueued *int64 `json:"total_queued,omitempty"`
		} `json:"queue_metrics,omitempty"`
	} `json:"metrics,omitempty"`
	Status    *DetailedHealthResponseStatus `json:"status,omitempty"`
	Timestamp *time.Time                    `json:"timestamp,omitempty"`
	Uptime    *string                       `json:"uptime,omitempty"`
}

// DetailedHealthResponseStatus defines model for DetailedHealthResponse.Status.
type DetailedHealthResponseStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Data *struct {
		Error *string `json:"error,omitempty"`
	} `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// GCResponse defines model for GCResponse.
type GCResponse struct {
	Data *struct {
		Duration *string `json:"duration,omitempty"`
	} `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Metrics *struct {
		ContentCount *int `json:"content_count,omitempty"`
	} `json:"metrics,omitempty"`
	Status    *string    `json:"status,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
	Uptime    *string    `json:"uptime,omitempty"`
}

// MetricsResponse defines model for MetricsResponse.
type MetricsResponse struct {
	AccessManagerStats *map[string]interface{} `json:"access_manager_stats,omitempty"`
	BackupCount        *int                    `json:"backup_count,omitempty"`
	BackupStats        *struct {
		LastBackupSize *int64 `json:"last_backup_size,omitempty"`
		TotalBackups   *int   `json:"total_backups,omitempty"`
	} `json:"backup_stats,omitempty"`
	ContentCount      *int   `json:"content_count,omitempty"`
	DatabaseSizeBytes *int64 `json:"database_size_bytes,omitempty"`
	GcStats           *struct {
		AvgDurationMs *int       `json:"avg_duration_ms,omitempty"`
		LastRun       *time.Time `json:"last_run,omitempty"`
		RunsCount     *int       `json:"runs_count,omitempty"`
	} `json:"gc_stats,omitempty"`
	HealthStatus *MetricsResponseHealthStatus `json:"health_status,omitempty"`
	LastBackup   *time.Time                   `json:"last_backup,omitempty"`
	QueueMetrics *struct {
		QueueDepth     *int   `json:"queue_depth,omitempty"`
		TotalErrors    *int64 `json:"total_errors,omitempty"`
		TotalProcessed *int64 `json:"total_processed,omitempty"`
		TotalQueued    *int64 `json:"total_queued,omitempty"`
	} `json:"queue_metrics,omitempty"`
}

// MetricsResponseHealthStatus defines model for MetricsResponse.HealthStatus.
type MetricsResponseHealthStatus string

// StorageRequest defines model for StorageRequest.
type StorageRequest struct {
	// AccessLimit Content expires after this many retrievals
	AccessLimit *int `json:"access_limit,omitempty"`

	// Data Content data as a string. Format depends on content type:
	// - text/plain: Plain text content
	// - application/json: Valid JSON string
	// - application/octet-stream: Base64-encoded binary data
	Data *string `json:"data,omitempty"`

	// ExpiresAt RFC3339 timestamp when content expires
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Id Unique content identifier (alphanumeric with dots, hyphens, underscores)
	Id string `json:"id"`

	// Tag Optional tag for categorization and filtering
	Tag *string `json:"tag,omitempty"`

	// Type MIME type of the content
	Type string `json:"type"`
}

// SuccessResponse defines model for SuccessResponse.
type SuccessResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
	Success *bool                   `json:"success,omitempty"`
}

// ListContentParams defines parameters for ListContent.
type ListContentParams struct {
	// Limit Number of items per page (max 1000)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Type Filter by content type (MIME type)
	Type *string `form:"type,omitempty" json:"type,omitempty"`

	// Tag Filter by content tag
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// CreatedAfter Filter content created after timestamp (RFC3339)
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// CreatedBefore Filter content created before timestamp (RFC3339)
	CreatedBefore *time.Time `form:"created_before,omitempty" json:"created_before,omitempty"`

	// IncludeExpired Include expired content in results
	IncludeExpired *bool `form:"include_expired,omitempty" json:"include_expired,omitempty"`
}

// CreateBackupJSONRequestBody defines body for CreateBackup for application/json ContentType.
type CreateBackupJSONRequestBody = BackupRequest

// StoreContentJSONRequestBody defines body for StoreContent for application/json ContentType.
type StoreContentJSONRequestBody = StorageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create manual database backup
	// (POST /api/v1/backup)
	CreateBackup(ctx echo.Context) error
	// Cleanup access trackers
	// (POST /api/v1/cleanup)
	CleanupAccessTrackers(ctx echo.Context) error
	// List content with advanced filtering and access count tracking
	// (GET /api/v1/content)
	ListContent(ctx echo.Context, params ListContentParams) error
	// Store new content with sequential write processing
	// (POST /api/v1/content)
	StoreContent(ctx echo.Context) error
	// Get total content count with storage-level optimization
	// (GET /api/v1/content/count)
	GetContentCount(ctx echo.Context) error
	// Delete content by ID with write conflict handling
	// (DELETE /api/v1/content/{id})
	DeleteContent(ctx echo.Context, id string) error
	// Retrieve content by ID with atomic access tracking
	// (GET /api/v1/content/{id})
	GetContent(ctx echo.Context, id string) error
	// Get content storage status with queue visibility
	// (GET /api/v1/content/{id}/status)
	GetContentStatus(ctx echo.Context, id string) error
	// Trigger manual garbage collection
	// (POST /api/v1/gc)
	TriggerGC(ctx echo.Context) error
	// Get comprehensive system metrics
	// (GET /api/v1/metrics)
	GetMetrics(ctx echo.Context) error
	// Trigger manual database synchronization
	// (POST /api/v1/sync)
	TriggerSync(ctx echo.Context) error
	// Basic health check with storage connectivity verification
	// (GET /health)
	HealthCheck(ctx echo.Context) error
	// Detailed health check with comprehensive system diagnostics
	// (GET /health/detailed)
	DetailedHealthCheck(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateBackup converts echo context to params.
func (w *ServerInterfaceWrapper) CreateBackup(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateBackup(ctx)
	return err
}

// CleanupAccessTrackers converts echo context to params.
func (w *ServerInterfaceWrapper) CleanupAccessTrackers(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CleanupAccessTrackers(ctx)
	return err
}

// ListContent converts echo context to params.
func (w *ServerInterfaceWrapper) ListContent(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListContentParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", ctx.QueryParams(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Optional query parameter "tag" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tag", ctx.QueryParams(), &params.Tag, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter tag: %s", err))
	}

	// ------------- Optional query parameter "created_after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_after", ctx.QueryParams(), &params.CreatedAfter, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter created_after: %s", err))
	}

	// ------------- Optional query parameter "created_before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "created_before", ctx.QueryParams(), &params.CreatedBefore, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter created_before: %s", err))
	}

	// ------------- Optional query parameter "include_expired" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "include_expired", ctx.QueryParams(), &params.IncludeExpired, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter include_expired: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListContent(ctx, params)
	return err
}

// StoreContent converts echo context to params.
func (w *ServerInterfaceWrapper) StoreContent(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StoreContent(ctx)
	return err
}

// GetContentCount converts echo context to params.
func (w *ServerInterfaceWrapper) GetContentCount(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetContentCount(ctx)
	return err
}

// DeleteContent converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteContent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteContent(ctx, id)
	return err
}

// GetContent converts echo context to params.
func (w *ServerInterfaceWrapper) GetContent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetContent(ctx, id)
	return err
}

// GetContentStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetContentStatus(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetContentStatus(ctx, id)
	return err
}

// TriggerGC converts echo context to params.
func (w *ServerInterfaceWrapper) TriggerGC(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TriggerGC(ctx)
	return err
}

// GetMetrics converts echo context to params.
func (w *ServerInterfaceWrapper) GetMetrics(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMetrics(ctx)
	return err
}

// TriggerSync converts echo context to params.
func (w *ServerInterfaceWrapper) TriggerSync(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(ApiKeyQueryScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.TriggerSync(ctx)
	return err
}

// HealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) HealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.HealthCheck(ctx)
	return err
}

// DetailedHealthCheck converts echo context to params.
func (w *ServerInterfaceWrapper) DetailedHealthCheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DetailedHealthCheck(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/backup", wrapper.CreateBackup)
	router.POST(baseURL+"/api/v1/cleanup", wrapper.CleanupAccessTrackers)
	router.GET(baseURL+"/api/v1/content", wrapper.ListContent)
	router.POST(baseURL+"/api/v1/content", wrapper.StoreContent)
	router.GET(baseURL+"/api/v1/content/count", wrapper.GetContentCount)
	router.DELETE(baseURL+"/api/v1/content/:id", wrapper.DeleteContent)
	router.GET(baseURL+"/api/v1/content/:id", wrapper.GetContent)
	router.GET(baseURL+"/api/v1/content/:id/status", wrapper.GetContentStatus)
	router.POST(baseURL+"/api/v1/gc", wrapper.TriggerGC)
	router.GET(baseURL+"/api/v1/metrics", wrapper.GetMetrics)
	router.POST(baseURL+"/api/v1/sync", wrapper.TriggerSync)
	router.GET(baseURL+"/health", wrapper.HealthCheck)
	router.GET(baseURL+"/health/detailed", wrapper.DetailedHealthCheck)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdeXPbOJb/Klj2/OHUShYl25mJqrZq5aMTb9ux11amZzv2yhD5JGEMAgwAKlFS/u5b",
	"OHhTshQfyfa4aqomFgngAXjH7/3wwP7mBTyKOQOmpNf/5slgBhE2/9zHwW0SX8CnBKTSP8SCxyAUAfN4",
	"bB6PGI5A/xmCDASJFeHM63tn5h+YoiCRikfIvozMyy0PvuAopuD1vQizBNO2fdzu+b1dr+WpRayfSSUI",
	"m3p3LY9EEYQEKzfQBCdUeX0lEmhVxv2ViwBQ9r4bN+9zzDkFzLy7u+wnPv4nBEoPk05YxpxJqM84xAov",
	"XYcYq5n+M59bR//UUbxTFSKfmGsryVcYjRfKdpj10PV7u77vt7wJFxFWXt8jTL0urBBhCqYgdE+BAKwg",
	"HGFVFkIvadvvtv3u0Pf75n9/eIUeQ6ygrYjZlpp4EUiJp1Du0a4ScgMimQQBSDlJKF009eGel/qwO7fO",
	"lvx4CQ70o821IkwE1jo5imTdOg7dQ8QnSM0ABXYMpDuwDwhDEaGUSAg4C2XRZnp7aymEgIjPIRwpgYNb",
	"EBXN2qs3WXv5B2Y5kes4E177EQrPsCGcKWANDgmbXkcBT+zT8pofJEIAU4gl0RiEXnkBShCYY1pa3p21",
	"VteNRUlEGsY6xV9IlEQIU8o/Q4js21Aap+vfb8aVGehnWjm0uUqFo7jkSh9k6akSV0a0S430U7Rle0Ih",
	"xMBCibQgixhelYR4B5TyFvqdCxr+W9NA8CUmAmTjBI/0s3un2O21d7rD3k5/701/7836UyRhWY0TCaLd",
	"7e20Qx4kkdaohkYKT5cvi8JTNOECBVjBlAvy1chektgMkg4gG0cwP9Q06Pj0yCxvqTcFX1Qnppiwek8r",
	"TOWESLWp/wpsU/NvosB6sb8ImHh975dOjhk6DjB0UrPM5cBC4IX+e0Koch4IhyGxyOC8NFxdIUvLMYhj",
	"SiBEaU+FRfnmERbQJISRVa3Q63sTTGVBBwrL1rRKS4z4feYozPxRDALF2hkWBt9rNGI+mUhYo0d5S+IY",
	"wmKHjf0prjCtdzfUPxf8me00wiqYETY1gcWuV8ntNIm8tutPNZ8S+WyO/lJhlchN9fe7rF2aoUxDlkRe",
	"/6P3KYHE7JBUXJh/MK5GE56w0Lsummb2fA2zXLm0VoY0OD3DIifsO5yDC7HZgLu9R9Aq0+2zzfwQFCYU",
	"wneAqZotX4JIyxPIpcC/oDTZjGamz0ahnWMdrbeGNjKPsYRNxwmJvB0ltcXe6/b8dXOKabDpoBRLNXLp",
	"zmOmIREXi4bJbJIgGUseFTaz7Ex/F0QBMi8h95KJ7RFnRHEjSauy/7bHEGKb+N0HN617Jsw45s/5cKV4",
	"stT9j0AILuT9USAWXBuFjgCuSTm8rLFUdkDXEYTrRp6iuaK8dTH49Hb3NpDAOd81h4c5CJT568KYe+vM",
	"uu4hmnxGPUDkxhDCVODQDJ6w9OdSjFhhODnefTyzSWLzpNRhd7bjR7t7cr1AdaQVaNPgYLRuSWwjXwHB",
	"lwAg1EClnCTphw+In3/HlIQ2eZgYv75uxDBgcb2Q8fbge2mAyi7s+ZF8wFzfYjHGU0ABpxQCM+fnyr6/",
	"O1puFvfuMb7/vyZ1atdn+QI6ZiHCDE9BmAC8InMqbVw+ioMm9bX+a5O3LQCZho0rxHRDVH53BLZO3fYk",
	"75Oqae2+Hzo186vfgYUa1gfPp6MK27c623IwSSTsETVTJEw2LEx3zWzP2tHoyeLb0wDDGqZbCdA2Q1kP",
	"x0wPhz1PA2IuFRd4CksPdlZzm2ksd0QewhMFAqkZ0RGdLZawqloPXcDXf/jW7iLC7C/+MvO9h5PEEmFk",
	"9WEb/VrjJ4OUqFvE0L9ibZQzQX10rv/P/JK+p9/AcUxJYIy580/JWR8ZYIH+6/LsvRup+hoPFKi2VAJw",
	"1Ef7WMLr3TawgIcQojFhWCyMtFfs8ajSi18PdnZ23uQ8Kfo8g3zCruljk6dlGT4w8imBbEwSAlNkQkCg",
	"LUzjGWZJBIIE6DNRMxRyJVtotohnwGQLJSwEIQMuQL6qE6YVnibCX06ATbUV9/b2Wl6MlQKhRfjfj7j9",
	"ddD+w2+/2R61r//9L2tzuNkBZTOJizBL2Uab+q2gdAvidX1/c4o3OwVyDOpSxveegcyhz6fEcqAf9Za5",
	"V66bnIBFgffj2Y1wRyNaPctOtZ4HpOrmECSCqMVlMIPIzmcQk99gMUiakvXB+TG6hQXCiZppJbaGjeYE",
	"oxngEMQ2unAra+3s6P1g/+RoNPgwfPcfWqxtr+URZkNgaAhXeyzu/aM9OD9u/waFSWIjiJ6kFem/ExCL",
	"jWT6pFugGAscgdLCDbSeMqzIHJDiKBs0lT6VzjTMhcMxGd02iaaXkLAJT3E7DiyqiDChepuSOOZC/afb",
	"me2AR3mnWu5L+4JGCkI3mCkVy36nU2jQcZ3Uuf53ZDprxyCMY2JB7mCkjVtIgtCpvnErwBSIWBAJaAJY",
	"JToi2fMAQ4BkB0otdwaHTFSTrbQgwcJsbcktY/JSB0WmCKaOosnplO0rdsV++QUdcDYh0/QE9ziKcaB0",
	"sNET34cZnhMurthwlgk6dj8iIvWGzAldIMImNAEW6AixQMDmRHAWWRK00H3fjvkLGpS1YKuggK90PPpd",
	"a+VNVS1v+mhAqZEMWBhzwpQ0+Xes0E3HwrWbVvbPTugo0RvkHElF+/RIFUkiUDMeyj66ybTuxqkd4gLd",
	"OB27qSpts9AmF3dS5xJjAShOxpQEdOH2kYwppGuTIoJL8hXQidlftHU6+Mfo4Oz98Oj9cHR5/MeRWaVD",
	"WzrSR13/dB9tdf3dv+399bWPTGpg3jgy5IQ9PiFOWzSkSQST6N1weI52fd+q3jwnHAxqTMW5wMqJobvZ",
	"Gr67OBsOT45GJ8enx0MzSHo8HHAWOJpQWDAm0VaYy+j7FZms8lbk6b1BQ87RqQZfDtPJ6tIMdZi5AO1f",
	"DV0g0dbg5OTs96PDbJGG/3N+dFlepZsqGGrl4ehGv3nMzCKUcFYqnpOuu4c+MGfrEKJTCAk24hg0REkA",
	"Lvo493F6PKy5DR4DkzwRAWxzMe24RrKj39XuH0QkzyaXIOYkgCXuxrzU0a6OqBIn5dAwurTGOjg/9lre",
	"HIS03qi77W/75lAvBoZj4vW9nW1/e8czMGRmQksHx6Qz73by/CbmctkBPiCMbNVT6oNc+E+zVatdPCug",
	"KvoD44NsN7JW5YQETLEIqXZzfIL2Bwe/fTgfHb8fHl38fXCCZDCDMKGwfcXOGF2gfFM0/NnH4RTE4X7m",
	"ZXWfwMJts09ZYcpxmM1jP61qcrq7z8NFgegx2KGiP3mB2X2nyeXas7s7C24sVjFr3vP9Rx/MQSEzWHnn",
	"VlUc3bW8Xb/7aMKUOdcGWSoOOIN8Wo7em+eTw/g56yAtpWtl2HvEjblXBrcved2Uo36NHN1nl4NxVTGr",
	"1JoMwCoiU6//sYxJP17ftb6VIeHH67trDYWjCOs/U//hvEfmL/LyQjyVGvmfZqAGZdhbetd6+NRVuaKt",
	"5b7q1AxCF0gJMp0Wyrz4BEmFKaSAKq0v08AzFjDXo9oDO0QB30rjsi5MMZpsaKnDmknl9WoxztrwhUh3",
	"Gmx27hHclZXclq0N03K4J/Qn1ZLBBoU5WF009+JTfpxPOWYmmaIpfLfnWQ+2XbfhFavZ0GrzBZg2FRid",
	"EKkQpjQDZAZKOMsxdhPjKWFpRhTOsclAMp7D5kACMDVEUCqsrcvQCaGIchjiYKLdLgNXW+mZngWvTbao",
	"JTzIeI4sG5BmSderv0JbEf5i0fGSvNYyl62CQmQ144Y3KRGRTSzqfaIobmq3lgzvyr8ax19ruF/NfujE",
	"sAis0VbGGL1azhE1CeTqCHNxasTRGhLge1iwxoFNo83HTQdN8ZbjmDOuc8vRn6/WKYBtEiwrs53Y8rhc",
	"xHXo0LXlHsOEC1hP8Dozu0pw2/MjSH5siycdY5ynckRHAZnQpXtbrbpsVPdlZ+vXTxl9G4pemyLwilJG",
	"E36fNeTYPDr3zogL55ZRwUm+wII/GywwEbsUretR2QTlUihOkXMBPaTqXIIOrSXg/lJpt8Tgc9Hc1QyQ",
	"XEgFEUpM+ViNC7XVcRpGGMQecCYNVg8WlpdI+5KuDMtmQHkvhdI0xREwmQho6uqiyG/1/B7a0tg9VhC+",
	"ykkPunBhocDD6YXSQ1u29oME9PZoiCroqfONhHcdV2arOApmENxmeYQD5Bbk1OCLWbgcv2zGfDiHbxye",
	"/m1UeD/XCHPQmB8FzTFNID+P8b5deWoGEVx5fXTlhVjcXnktdOVRzKYJnrrfgV15d549tvMsg9Te3Xtd",
	"ZPor8plzFPiimoWqn5U2iFY90DSDN9Zd4+mKqxHFan1jXmvZb+VQ+658GqZEAnUGqfdo3qN6mrYi3hRN",
	"w8r87OGmViqnow1xMUikK/gTxZruzvPJ0VirWD1NsMHIyrb3/LKZdIBx47YbefyXCP1oEboeK21Svfyg",
	"8L6oXE/oO1nhVmNa/xaUic6qUvds75zkMdzkpjZ281iRiHzVwNY6mTaFOVCLH2y1DJYqJ05biHHdgShb",
	"X1MMfAtpBm/ujjwpkVa6nLLCIFbeHHlBzX82mzQGYYwhKCmAtcySwjtDSG9mbmqYGitag6SgGop4Ds3v",
	"SMYQkAkJMnnGC3R8iCaCRxZXp6ULFl8bOQlTQCmZgtPcBaJ8SgKDDKxL0cCNkkBZDn2QKB5hrVaUpmV2",
	"EhnBzI3xSe4IJHLnynSBxqD9ge5QAdN41wCQ7ewQescNjpWCKDZj1UzeznJN3i5d2uNDPZpbuPtKvAzD",
	"YD6hkBMMoVeFcEUw+KCisCclIDYAg3Z1fhL2Icg3znFJP5Pn9HefH2dpiGXver747sfy3c5jlh2lcYhl",
	"p4dmmIV0LZKjETRdODCwzDdbskXxiATVc45A2GMYzMJCCZklCtJCsJSj2PV3i6430xidUikSQdvxowVa",
	"Y7frF5vMsEQCcDCDEBElS4Vqq/HX+p74T+d/MaVnEzPljTxxa1mV61pfNqiXml6vcB6r0OiLd/+ZvLu2",
	"1fQYw6T0/vMLU7T61B28RJ1HizpZNLg3CKzLrS9JFjr5FarGsHRg2GZT7u9KP7PcwDLSfFImGuZEkjGh",
	"RC10xsCXsfKVOmX70QxkKFpprr5Y3rGPCiw9YaUu8Gdsa1bzvnRDyzKUGsYgpD02M0cTc0woHlN7NJDd",
	"/9Fts49l5M2PD1HIQRrrM7U+K0OcncdmKUdK6LuW/zqJR/MHU1ZxnCu/NfISqV7ykD83h1S7WWLtwfhd",
	"6xNz77tBPJgGG9RVZmWc0/qlfsWRgIBiEqGQyFskYxyA8bkpv4sKF2WM439greTQSvX24Clp3cJnFBq2",
	"e/2PG7wQuz/OKBt2Ka29fqBhOhVMy5zrZrFZzWThdvhqniC9/JSStOlXgPLrZKn92NtSraLtGddBpCKB",
	"bDkDdeJgWmB6nZG6j0CgORYLpI0/RJxl3ROt7HpO7q5XZr+x4HMSgjTwMeKmciSKBcyASTLPvlv0aglr",
	"4EZ9Ssuuft2iQXHSub8c1vxLBdqinpYNrGDO9uMy6Crx/d5rdJp/eqtk0XLBNgmwOA+xuuVMcJZe8s5M",
	"xNYvuYSsYn/EfmMgGSOdzyAcKO2Wql3ZsxubG2mnAOE2GtDPeJFf13N6bm+b8yjGykGLFYH4Us/1x55V",
	"aBFeIvDPZ61mX+o3nx43+i4znTVjsI2US2PvpTE1F09d3p5e+0VqhhWagyATAjJ1Sc4QyByYNiUdacdY",
	"kqBQv8eYhglzohbG0ijH+h2qo7SwLfJv+hm7f8+rl+yz8gf0niOR7bWpxbRfom0yWeu9DMHzlCZb+QJX",
	"k2bYtbLXzamaLezV9hReyMIdaqsv2e7vm7Us7UfxTL28unZvgqo+3OPEK1fNlxNlpZBRF2kJXGtlsoYE",
	"TxkvQDIc4th8IsHUlbpcL+AhyIeowRUz3TnC7UB3Z/i2nu+js9/sVXYrYrYd9vFrdI6F4fFcPtlHl3Yq",
	"6ZeW0DhRaJKwwOJI3WzP30HuojP6wDLmLWuafZmp8RS/+MHTJ9fTJd9XbfRkRvZcX7Uv7fmvf6go2eeu",
	"jF/f+aGy5N/bKptr2leDeTQiroJJrGmwJppob9JEux7CHCiPjeu3b5Wu7vc7HcoDTGdcqv7f/L91vfr1",
	"k3PBw8Smjw09yH6n8003ZziCO1NyLIjWd6Os6YPSjRMPx2S7+GGSO8O5urnWnMzFh8M8hqbQrEQK5bxw",
	"A+1Tn5C9Cdwy8bKF3h5Y11P7DzzIvNvm+Fnv+V1hj20cq+Fo1+PSDb27vvu/AAAA///IFOh+8GUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
